// Code generated by script/generate; DO NOT EDIT.

package patch

//go:generate go run ../../../script/generate runtime-def
const RuntimeExtraDef = `
// xgo
func __xgo_getcurg() unsafe.Pointer
func __xgo_is_system_stack() bool
func __xgo_trap(pkgPath string, identityName string, generic bool, recv interface{}, args []interface{}, results []interface{}) (func(), bool)
func __xgo_trap_for_generated(pkgPath string, pc uintptr, identityName string, generic bool, recv interface{}, args []interface{}, results []interface{}) (func(), bool)
func __xgo_trap_var_for_generated(pkgPath string, name string, tmpVarAddr interface{}, takeAddr bool)
func __xgo_set_trap(trap func(pkgPath string, identityName string, generic bool, pc uintptr, recv interface{}, args []interface{}, results []interface{}) (func(), bool))
func __xgo_set_trap_var(trap func(pkgPath string, name string, tmpVarAddr interface{}, takeAddr bool))
func __xgo_register_func(info interface{})
func __xgo_retrieve_all_funcs_and_clear(f func(info interface{}))
func __xgo_init_finished() bool
func __xgo_on_init_finished(fn func())
func __xgo_on_gonewproc(fn func(g uintptr))
func __xgo_on_goexit(fn func())
func __xgo_on_test_start(fn interface{})
func __xgo_on_test_end(fn interface{})
func __xgo_get_test_starts() []interface{}
func __xgo_get_test_ends() []interface{}
func __xgo_peek_panic() interface{}
func __xgo_mem_equal(a, b unsafe.Pointer, size uintptr) bool
func __xgo_get_pc_name(pc uintptr) string`