// Code generated by script/generate; DO NOT EDIT.

package patch

//go:generate go run ../../../script/generate ../../..
const RuntimeExtraDef = `
// xgo
func __xgo_getcurg() unsafe.Pointer
func __xgo_trap(pkgPath string, identityName string, generic bool, recv interface{}, args []interface{}, results []interface{}) (func(), bool)
func __xgo_set_trap(trap func(pkgPath string, identityName string, generic bool, pc uintptr, recv interface{}, args []interface{}, results []interface{}) (func(), bool))
func __xgo_register_func(pkgPath string, fn interface{}, recvTypeName string, recvPtr bool, name string, identityName string, generic bool, recvName string, argNames []string, resNames []string, firstArgCtx bool, lastResErr bool)
func __xgo_for_each_func(f func(pkgPath string, recvTypeName string, recvPtr bool, name string, identityName string, generic bool, pc uintptr, fn interface{}, recvName string, argNames []string, resNames []string, firstArgCtx bool, lastResErr bool))
func __xgo_init_finished() bool
func __xgo_on_init_finished(fn func())
func __xgo_on_goexit(fn func())`