// Code generated by xgo. DO NOT EDIT.
// the above line is to avoid gofmt to simplify
// the ((lock)) to (lock)
package mock_var

var countParenNested int

// NOTE: if lock is captured, this function will
// panic: fatal error: sync: unlock of unlocked mutex
func incrLocked_ParenNested() {
	// ((x)) will be simplied to (x)
	f := ((lock)).Lock
	f()
	countParenNested = countParenNested + 1
	lock.Unlock()
}