// Code generated by script/generate; DO NOT EDIT.

package patch

const sig_gen__xgo_trap = `func(pkgPath string, identityName string, generic bool, recv interface{}, args []interface{}, results []interface{}) (func(), bool)`