// Code generated by script/generate; DO NOT EDIT.

package syntax

const sig_gen__xgo_register_func = `func(pkgPath string, fn interface{}, recvTypeName string, recvPtr bool, name string, identityName string, generic bool, recvName string, argNames []string, resNames []string, firstArgCtx bool, lastResErr bool)`