package exec_tool

const GO_BYPASS_XGO = "GO_BYPASS_XGO"

const XGO_COMPILER_SYNTAX_REWRITE_ENABLE = "XGO_COMPILER_SYNTAX_REWRITE_ENABLE"
const XGO_COMPILER_SYNTAX_REWRITE_PACKAGES_FILE = "XGO_COMPILER_SYNTAX_REWRITE_PACKAGES_FILE"
const XGO_COMPILER_SYNTAX_REWRITE_PACKAGES_SUM_FILE = "XGO_COMPILER_SYNTAX_REWRITE_PACKAGES_SUM_FILE"

const XGO_COMPILER_BIN = "XGO_COMPILER_BIN"
const XGO_COMPILER_ENABLE = "XGO_COMPILER_ENABLE"
const XGO_DEBUG_DUMP_IR = "XGO_DEBUG_DUMP_IR"
const XGO_DEBUG_DUMP_IR_FILE = "XGO_DEBUG_DUMP_IR_FILE"
const XGO_DEBUG_DUMP_AST = "XGO_DEBUG_DUMP_AST"
const XGO_DEBUG_DUMP_AST_FILE = "XGO_DEBUG_DUMP_AST_FILE"
const XGO_DEBUG_VSCODE = "XGO_DEBUG_VSCODE"

const XGO_TOOLCHAIN_VERSION = "XGO_TOOLCHAIN_VERSION"
const XGO_TOOLCHAIN_REVISION = "XGO_TOOLCHAIN_REVISION"
const XGO_TOOLCHAIN_VERSION_NUMBER = "XGO_TOOLCHAIN_VERSION_NUMBER"

const XGO_MAIN_MODULE = "XGO_MAIN_MODULE"

// --strace
const XGO_STACK_TRACE = "XGO_STACK_TRACE"

// --strace-dir
const XGO_STACK_TRACE_DIR = "XGO_STACK_TRACE_DIR"

// --strace-snapshot-main-module-default
const XGO_STRACE_SNAPSHOT_MAIN_MODULE_DEFAULT = "XGO_STRACE_SNAPSHOT_MAIN_MODULE_DEFAULT"

const XGO_COMPILE_PKG_DATA_DIR = "XGO_COMPILE_PKG_DATA_DIR"

const XGO_STD_LIB_TRAP_DEFAULT_ALLOW = "XGO_STD_LIB_TRAP_DEFAULT_ALLOW"

const XGO_DEBUG_COMPILE_PKG = "XGO_DEBUG_COMPILE_PKG"
const XGO_DEBUG_COMPILE_LOG_FILE = "XGO_DEBUG_COMPILE_LOG_FILE"

const XGO_COMPILER_OPTIONS_FILE = "XGO_COMPILER_OPTIONS_FILE"

// xgo's original working dir
const XGO_SRC_WD = "XGO_SRC_WD"

// flags automatically applied when `xgo` runs
const XGO_FLAGS = "XGO_FLAGS"
