name: Debug NoXPos

on:
  push:
    branches: [ "master", "dev-go1.25" ]
  pull_request:
    branches: [ "master" ]

jobs:
  debug-noxpos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Run run-test
      run: go run ./script/run-test --install-xgo --reset-instrument --log-debug -v
