# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  tests:
    strategy:
      matrix:
        os: [ windows-latest ]
        go: [ '1.24' ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.go }}'

    - name: Test
      run: go run ./script/run-test --install-xgo --with-setup --reset-instrument --log-debug -v