# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: false

    - name: Check spelling of files
      uses: crate-ci/typos@master
      continue-on-error: false
      with: 
        files: ./
      
    - name: Binary Install
      continue-on-error: false
      run: curl -fsSL https://github.com/xhd2015/xgo/raw/master/install.sh | env INSTALL_TO_BIN=true bash -x
    
    - name: Check Binary Install
      continue-on-error: false
      run: xgo revision
      
    - name: Build
      run: go build -o /dev/null -v ./cmd/xgo

    - name: Test
      run: go run ./script/run-test --reset-instrument --debug -v -cover -coverpkg github.com/xhd2015/xgo/runtime/... -coverprofile cover.out

    - name: Merge Coverages
      run: go run ./script/cover merge ./cover-runtime.out ./cover-runtime-sub.out -o cover-runtime-merged.out

    - name: Print coverage
      run: cd runtime && go tool cover --func ../cover-runtime-merged.out

    - name: Build Release
      run: go run ./script/build-release --include-install-src --include-local
    
    - name: Check Version
      run: ~/.xgo/bin/xgo revision

    - name: Check Go Version
      run: ~/.xgo/bin/xgo exec go version