name: Go 1-17

on:
  push:
    branches: [ "dev-go1.25" ]

jobs:
  test-go1-17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.17'
    - run: go run ./script/run-test --install-xgo --with-setup --reset-instrument --log-debug -v
